before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: W59r/2+AcToQa0zm8PjbnTbksAmut8Iomq9v6/XIqi0TDmG15dtp3uiiKS6miWarONAArwNRKivqX0gITjJQ/CRHd5tWz9j2nZE6JVKY/MkGUDvL2QmUoN/vZsvE4UkWL9kHcSFCsM+hXxZV1uSDJRmFRo1hjuo0gI+YPDvbiAeccu34kKTF3JLIubJdupNTTfTXmbjmorgsr4sR8YMvi5Tnf6yLLiPkzm2MGbkilSI3XJ9t42LRXrEkmymhuPsQ2iyD1H3AAhJYhgNFPe31kDY/IMRkVDD72Gl1o1NRxA5pxdqKOjneeELQShq+HzV+hMOmoNOMbA00F7A/awqPnVwetJ5Gkecc5iP/LNXzcDGnoDh1pO03tufq6BNzuTtQCa+MiNpaDNU0niZt+5Z5YdRwRhiHfwhJE9JSrbeR0FuMaxRk2mcPEiy3w/+qG1nIek6oAGvynYGqPRnE/Jzd0qQZi3ivKOuSHegcOsj/zDbmjfLDDLiHWiJe8O6UWN3e0FKAhBLZpV5QrhM41kf7gOyNvn+zhcXeE7K2psYmjFhbh/3oxnhyVDDlYHI3+1u4mKPPBjnjEWZKm+crX9368tBwgBunusEBN0wnstDnWlRuQUOqZJPZsTUq1EJHgq24rpnKfHzUDGOCB5ioX8GJ9LLUlHoQar4AKyM91kkohGg= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
